import data_validation as da

def test_data_validation():
    print('test for data_validation')
    print('-------------------') 
    print('check less than 4 digits, Expected result is: False')
    print("Actual result is:")
    print(da.num_length(67))
    print('----')
    print('check more than 4 digits, Expected result is: False')
    print("Actual result is:")
    print(da.num_length(67569))
    print('----')
    print('check 4 digits, Expected result is: True')
    print("Actual result is:")
    print(da.num_length(6754))
    print('-------------------')
    print('check number 4, Expected result is: True')
    print("Actual result is:")
    print(da.is_square(4))
    print('----')
    print('check number 9, Expected result is: True')
    print("Actual result is:")
    print(da.is_square(9))
    print('----')
    print('check number 8, Expected result is: False')
    print("Actual result is:")
    print(da.is_square(8))
    print('-------------------')
    print('check \'Ofer Rotem\', Expected result is: True')
    print("Actual result is:")
    print(da.valid_name('Ofer Rotem'))
    print('----')
    print('check \'Ofer rotem\', Expected result is: False')
    print("Actual result is:")
    print(da.valid_name('Ofer rotem'))
    print('----')
    print('check \'ofer Rotem\', Expected result is: False')
    print("Actual result is:")
    print(da.valid_name('ofer Rotem'))
    print('----')
    print('check \'ofer rotem\', Expected result is: False')
    print("Actual result is:")
    print(da.valid_name('ofer rotem'))
    print('----')
    print('check \'Ofer Nir Rotem\', Expected result is: False')
    print("Actual result is:")
    print(da.valid_name('Ofer Nir Rotem'))
    print('----')
    print('check \'OferRotem\', Expected result is: False')
    print("Actual result is:")
    print(da.valid_name('OferRotem'))
    print('----')
    print('check \'Ofer\', Expected result is: False')
    print("Actual result is:")
    print(da.valid_name('Ofer'))
    print('-------------------')
    print('check 33, Expected result is: False')
    print("Actual result is:")
    print(da.even_odd_digits(33))
    print('----')
    print('check 491, Expected result is: False')
    print("Actual result is:")
    print(da.even_odd_digits(491))
    print('----')
    print('check 10, Expected result is: True')
    print("Actual result is:")
    print(da.even_odd_digits(10))
    print('----')
    print('check 122, Expected result is: True')
    print("Actual result is:")
    print(da.even_odd_digits(122))
    print('----')
    print('check 0, Expected result is: True')
    print("Actual result is:")
    print(da.even_odd_digits(0))
    print('----')
    print('check 184, Expected result is: True')
    print("Actual result is:")
    print(da.even_odd_digits(184))
    print('----')
    print('-------------------')
    print('-------------------')